---
title: "Assignment 3: Regression models"
output:
  html_document:
editor_options: 
  chunk_output_type: console
---

# Introduction 

Regression models are extreamly flexible and the working horse of statistics! We will attempt to understand them better in this course as they are very common in data analysis. This weeks assignment is composed of several parts, one of which is optional (meaning you do not have to do them).

# Part 1: t-tests and regression analysis

In the last assignment you were expected to perform a t-test to compare the HIGH and LOW group in some variable. Here I would like you to compare `AVG_CSA_T1` between the HIGH and LOW group with a simple t-test and compare your results to a regression model using CLUSTER as a predictor.

Make sure that you use `var.equal = TRUE` in your t-test when comparing with the regression model. How do you interpret the results of the regression model? Do you get the same answer?

Write up the results with a short introduction including a question (and some background information if you like). The results from the regression model can be displayed as a table with the coefficients, SE, t- and p-values. See if you find inspiration in the `broom` package.

# Part 2: Is there a relationship between muscle size and strength

The Haun et al. 2019 data set contains a variable for muscle strength `Squat_3RM_kg`. In this assignment I want you to estimate the relationship between msucle mass and strength. There are several muscle mass meassures in the data set at time 1 (T1). Select one or more of these varaibles and estimate the relationship between muscle mass and strength. Think about the relationship as a bigger muscle could produce more force, muscle mass is the predictor and muscle strength is the dependent variable. Use the whole data set!

# Calculate lactate thresholds (Optional)

Using the data you collected in the physiology lab. Estimate the exercise intensity at 4 mmol blood lactate. Make use of the code in the second lesson this week.

# How to hand in?

As always, I preffer a githiub submission. But a R-markdown file AND an html-file on canvas is OK. I would like to have a report (html-file) without any code and the R-markdown file for reference (where I can read the code). Try to make the report and figures to look elegant!

Good luck!